apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-crud-k8s
          image: snjara/azure-training-image4:latest
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
               configMapKeyRef:
                 name: springboot-config
                 key: DB_HOST
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
               configMapKeyRef:
                 name: springboot-config
                 key: DB_NAME

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
               configMapKeyRef:
                 name: springboot-config
                 key: DB_USER

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
               secretKeyRef:
                 name: mysql-secret
                 key: DB_PASS
              
            - name: DB_PORT # Setting Database password from Secret
              valueFrom:
               configMapKeyRef:
                 name: springboot-config
                 key: DB_PORT
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-crud-svc-test
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.

